version: '3.3'
services:
  db:
    image: mariadb:latest
    container_name: prestashop-db
    platform: linux/arm64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:latest
    container_name: prestashop
    platform: linux/arm64
    ports:
      - "8789:80"
    restart: always
    environment:
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: 1
      DB_SERVER: db
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
      PS_DEV_MODE: 1
      PS_DOMAIN: localhost:8789
      PS_FOLDER_ADMIN: admin123
      PS_FOLDER_INSTALL: install123
    volumes:
      - ./prestashop:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    platform: linux/arm64
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin

volumes:
  db_data:
