version: '3.8'

services:
  db:
    platform: linux/arm64  # Specify platform for ARM architecture
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps

  prestashop:
    platform: linux/amd64  # Assuming PrestaShop image supports multi-platform
    depends_on:
      - db
    image: prestashop/prestashop:latest
    ports:
      - "8789:80"
    restart: always
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      DB_SERVER: db
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
      PS_DEV_MODE: 0
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin123
      PS_FOLDER_INSTALL: install
    volumes:
      - .:/var/www/html

  phpmyadmin1:
    container_name: docker-pmab
    platform: linux/amd64  # Specify platform for PHPMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8181:80"
    environment:
      - PMA_HOST=db

volumes:
  mysql_data:  # Named volume for MySQL data persistence

networks:
  default:
    driver: bridge
