<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2FLlB5o\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2FLlB5o/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2FLlB5o.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2FLlB5o\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2FLlB5o\appAppKernelProdContainer([
    'container.build_hash' => '2FLlB5o',
    'container.build_id' => 'fb11a8be',
    'container.build_time' => 1719947535,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2FLlB5o');
