<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVk1xg4P\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVk1xg4P/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVk1xg4P.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVk1xg4P\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVk1xg4P\appAppKernelProdContainer([
    'container.build_hash' => 'Vk1xg4P',
    'container.build_id' => '0bd3837a',
    'container.build_time' => 1719865989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVk1xg4P');
