<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwwGLwU0Q+IybpSulfd5j'."\n".'ygdfkQxTtU/WhJEDLfGvAKhE/je5hYWaQAv8mrNCpUlJkxC1/ynlMdZKL+hslW5C'."\n".'zFLdJ9CTTzI5pHn47jpXhgsQW6chkP/K4o4aTMe/2jBMe1LGnmIzCckAJLgvg20L'."\n".'H81tY0JuJIYkCB+l0C/zWQGxfV7qb+PV9ZQAFl6nrB+VaCXBDxoNa6/DMWrzCz+z'."\n".'oBbheD18OnwP6nXpQ5uUT4n4IJIVNPAg8IvG0JNQ9ths4K/be8zrhx/0JZD4Uyex'."\n".'BN276zoKkC3hN7CmzmW8NNSDm5LMDPjf4lGeinaHYgDKaDRVE8Y6bZ9/8UPxYTGu'."\n".'pwIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
