<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ITJy8i\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ITJy8i/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ITJy8i.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ITJy8i\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container5ITJy8i\appAppKernelDevDebugContainer([
    'container.build_hash' => '5ITJy8i',
    'container.build_id' => '947036d4',
    'container.build_time' => 1719866139,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ITJy8i');
