<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW29mjFQ\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW29mjFQ/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW29mjFQ.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW29mjFQ\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerW29mjFQ\appAppKernelDevDebugContainer([
    'container.build_hash' => 'W29mjFQ',
    'container.build_id' => 'db1cf589',
    'container.build_time' => 1719951716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW29mjFQ');
